language: java
jdk:
  - oraclejdk8

sudo: enabled
dist: trusty

script:
  - mvn clean verify

notifications:
  email: true

before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"
  # Add tag and push to master.
  - git tag -a v${TRAVIS_BUILD_NUMBER} -m "Travis build $TRAVIS_BUILD_NUMBER pushed a tag."
  - git push -q https://$TAGPERM@github.com/melissayan/travis_ci_test/ --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: b8a7496a420e78ee5d09d63265fd18e87a90e83b
  file:
    - "target/travis-build-test-1.0-SNAPSHOT.jar"
    - "target/GenomeAnalysisTK.jar"
  on:
    repo: melissayan/travis_ci_test

#after_success:
  #- git config --global user.email "travis@travis-ci.org"
  #- git config --global user.name "travis-ci"
  # Add tag and push to master.
  #- git tag -a v${TRAVIS_BUILD_NUMBER} -m "Travis build $TRAVIS_BUILD_NUMBER pushed a tag."
  #- git push origin --tags
#  - ls -R
#  - git fetch origin