language: java
jdk:
  - oraclejdk8
sudo: enabled
dist: trusty
notifications:
  email: true

script:
  - export JARNAME="variantQC"
  - export VERSION=""
  - mvn -Djar.finalName=$JARNAME -Dversion=$VERSION clean verify

after_success:
#  - git describe --tags $(git rev-list --tags --max-count=1)
#  - git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=1
#  - echo "$TRAVIS_TAG and $TRAVIS_BUILD_NUMBER"
  - export JARFILE="$JARNAME-v$VERSION.jar"
#  - echo "$JARNAME and $JARFILE"
  - chmod 600 deploy-key
  - mv travis_ci_deploy_key ~/.ssh/id_rsa
  - git remote add deploy ssh://git@github.com:melissayan/travis_ci_test.git
  - git push deploy
  - cp target/$JARNAME-$VERSION.jar target/$JARFILE
  - echo "$TRAVIS_TAG and $TRAVIS_BUILD_NUMBER"
  - git tag v$TRAVIS_BUILD_NUMBER -a -m "Travis build $TRAVIS_BUILD_NUMBER pushed a
  tag."
  - git push origin v$TRAVIS_BUILD_NUMBER

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "$TRAVIS_CI_DEPLOY_KEY_GIT"
  file:
    - target/$JARFILE
    - target/$JARNAME-$VERSION.jar
  on:
    repo: melissayan/travis_ci_test
    all_branches: true
    tags: false
after_deploy:
  - echo "$TRAVIS_TAG and $TRAVIS_BUILD_NUMBER"

branches:
  except:
  - "/^*-v[0-9]/"

before_install:
- openssl aes-256-cbc -K $encrypted_d6cb3e44f727_key -iv $encrypted_d6cb3e44f727_iv
  -in travis_ci_deploy_key.enc -out ~\/.ssh/travis_ci_deploy_key -d
